= Node.js sample application
:toc:

Node.js sample application. Developed to be used with OpenShift and other Kubernetes platforms, but can be used without Kubernetes.

== Local

* Build:
** `docker build -t nodejssample .`
* Run in foreground:
** `docker run -it --rm --name nodejssample -p 8080:8080 nodejssample`
* Run in background:
** `docker run -d --name nodejssample -p 8080:8080 nodejssample`

== Docker Hub

This is available from Docker Hub: https://hub.docker.com/r/kazhar/nodejs-sample.

* Pull:
** `docker pull kazhar/nodejs-sample`
* Run:
** `docker run -it --rm -p 8080:8080 kazhar/nodejs-sample`

== OpenShift

=== Deploy application

Application can be deployed from container image or directly from (GitHub) source. The Container image may be given as tar-file (for example: _nodejssample.tar.gz_) or it is available from registry.

Here we create image directly from GitHub source.

* Login to OCP and create a new project.
* Create new app and specify docker image:
** `oc new-app https://github.com/samisalkosuo/nodejs-sample -l app=nodeapp --name nodeapp -e APP_NAME=nodepp -e DEBUG=true`
*** Option `--name nodeapp` sets the name for the resources.
*** Environment variables are set also. For example, option `-e APP_NAME=mynodepp`.
*** Creating from existing image is done using: `oc new-app --docker-image=docker.io/kazhar/nodejs-sample:0.1 -l app=nodeapp --name nodeapp -e APP_NAME=nodepp -e DEBUG=true`
*** Note: If using private registry, OpenShift must be able to pull images from the private registry, see https://docs.openshift.com/container-platform/4.3/openshift_images/managing_images/using-image-pull-secrets.html#images-update-global-pull-secret_using-image-pull-secrets[Using image pull secrets].
* Creating new-app created also service:
** `oc describe svc nodeapp`
* But route is not created automatically. So let's create it:
** `oc expose svc nodeapp`
* Check the route URL:
** `oc get route`
* Go to that route URL.
* Delete application, if not needed anymore:
** `oc delete all -l app=nodeapp`
** Deletes all resources that have the specified label.

==== Secure route

The default OCP route is unsecured and does not accept TLS. This is the case at the time of writing and OCP version 4.6.19.

* https://docs.openshift.com/container-platform/4.3/networking/routes/secured-routes.html[OCP documentation] shows how to add custom certificate and use either edge or reencrypt.
* Or you can use existing ingress certificate by patching route to set termination to edge and redirect if using plain http:
** `oc patch route nodeapp -p '{"spec":{"tls":{"insecureEdgeTerminationPolicy":"Redirect","termination":"edge"}}}'`

==== Update deployment

* Since deployment was created from GitHub source, update is done using:
** `oc start-build nodeapp`

== Usage

Nodejs-sample app has various endpoints.

* `/endpoints` - JSON of endpoints.
* `/test` - dummy test page.
* `/calculatepi` - calculates digits of Pi (10-20000). Specify digits with parameter `?digits=12345`.
* `/killserver` - kills server.
