apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-sample-pv-claim
spec:
  #comment this to use default storageclass
  storageClassName: ocs-storagecluster-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi