apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-sample-pv-claim
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  #comment this to use default storageclass
  storageClassName: rook-ceph-fs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi